# Generated by Django 3.2.9 on 2021-11-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=256)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_categories', to='clients.clcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CLProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='clproducts')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clients.clcategory')),
            ],
        ),
    ]
