# Generated by Django 3.2.9 on 2021-11-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clcategory_clproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcategory',
            name='link',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='clproduct',
            name='link',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
